name: proyecto_final_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'  # Actualizamos el SDK de Dart para habilitar la seguridad de nulos

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: 1.2.1
  youtube_player_flutter: ^9.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1  # Cambiamos la versión de latlong2
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icono.png
    - lib/assets/voluntario.png
    - lib/assets/adal.png
    - lib/assets/leo.png



